services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: '!Univega1986'
      POSTGRES_USER: matt
      POSTGRES_DB: sumo
    volumes:
      - type: bind
        source: /data/postgres_data/sumo
        target: /var/lib/postgresql/data
