name: Deploy REST API to Google App Engine (GAE)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Create ormconfig
        run: |
          touch ormconfig.json
          echo "${{ secrets.GCP_ORMCONFIG }}" | base64 --decode >> ormconfig.json

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.GCP_ENV }}" | base64 --decode >> .env

      - name: Install dependencies
        run: npm install

      - name: Build Node Project
        run: npm run tsc

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy app.yaml --quiet